### PR TITLE
make text great again (and yellow too)

### PR DESCRIPTION
**Pull request by benabraham**
i think this is much GREATER than before!

### CODE REVIEW

**Comment by Mnau-mnau** [comment]
I just hate yellow, can you please change it to orange?

**Comment by DinoVas** [comment]
White , red and blue would be even greater.

**Comment by benabraham** [comment]
Let's do that all!

**Comment by Mnau-mnau** [comment]
can we do the rainbow?

**Comment by bossman88** [comment]
Mollit nostrud adipisicing et enim aliqua consectetur id deserunt ipsum laborum veniam occaecat exercitation occaecat. Esse reprehenderit tempor adipisicing amet consequat. Tempor adipisicing cillum officia magna ipsum irure occaecat occaecat minim exercitation reprehenderit. Ea aliquip deserunt incididunt exercitation do ipsum. Deserunt incididunt eiusmod labore sint culpa culpa dolor et consequat aute non adipisicing. Sit dolore cupidatat minim et exercitation culpa ad.

**Comment by benabraham** [comment]
Should the rainbow be the double one?

**Pull request merged**
